### ISSUE TITLE
IE 11 compatibility

### ISSUE THREAD

**Issue by pavelekNET** [nobrainr/morphism#130]
**Describe the bug**
In IE 11 file morphism.js throws "Invalid syntax (1,1715)"

**To Reproduce**
1. reference `<script src="https://unpkg.com/morphism/dist/morphism.js"></script>`
2. Open in IE 11

**Expected behavior**
Work like in other browsers

**Additional context**
If possible could you specify at least polyfills that are required for this library? I found out that its used: Promise, Map

Many thanks

**Comment by priithansen** [comment]
There are also arrow functions in production build that IE doesn't support

**Comment by emyann** [comment]
Thank you guys for digging this issue! I'm gonna work on a PR by the end of the week, when I'll be able to test on IE11.

**Comment by priithansen** [comment]
I was able to produce a IE compatible build with:

```
npm i --save-dev @babel/plugin-transform-runtime
npm i --save-dev @babel/runtime
```

and modifing the .babelrc file so:

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current",
          "esmodules": true,
          "ie": "11", // Added !
        }
      }
    ],
    "@babel/typescript"
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/proposal-class-properties", { "loose": true }],
    "@babel/proposal-object-rest-spread",
    "@babel/plugin-transform-runtime" // Added !
  ]
}
```

But this result still needs unspecified polyfills (ex: Symbol) and will not work if transpiled again on import by the consumer script. Also the file size will end up ~2x the original size.

Can't speak for other people but for my use case it would make most sense if the npm install of morphism would include js source so that I could import and tell webpack to transpile it and use whichever polyfills or targets are specified for the whole project.

**Comment by sisp** [comment]
@emyann Have you considered using [TSDX](https://github.com/jaredpalmer/tsdx) for zero-config build/test setup? It follows the spirit of Facebook's [Create React App](https://github.com/facebook/create-react-app) but for (Typescript) libraries instead of React apps. Many great projects like [Formik](https://github.com/jaredpalmer/formik), [mobx-keystone](https://github.com/xaviergonz/mobx-keystone), [mobx-react-lite](https://github.com/mobxjs/mobx-react-lite), etc. are using it and my personal experience has been great, too. It takes care of many peculiarities out of the box and is easily extensible if needed. Perhaps it also helps with IE11 compatibility?
