### ISSUE TITLE
[Question] How to construct an object with projection

### ISSUE THREAD

**Issue by C-Higgins** [nobrainr/morphism#147]
The documentation is clear about how to grab a piece of data from a nested object. But what if you need the opposite: to construct a nested object from a piece of data?

```typescript
interface source {
  id: string;
}
interface target {
  foo: {
    id: string
  }
}
```

I know I can use the function technique like this:

```typescript
createSchema<target, source>({
  foo: (i) => ({id: i.id}),
}
```

I'm wondering if there is a way to do this with a simple string argument though (which I, maybe falsely, assume to be faster)?

**Comment by C-Higgins** [comment]
And as an unrelated question, I don't understand how the `source` and `target` function params are meant to be used here:

```typescript
ActionFunction<D = any, S = any, R = any> {
    (iteratee: S, source: S[], target: D): R;
}
```

From what I can tell, source is just the iteratee wrapped in an array, and target is an empty object at the function execution time, since the target will not have been constructed yet from the morph. How are these things meant to be used?

**Comment by emyann** [comment]
@C-Higgins Thank you for using `Morphism`!

For your first question, I realize it's in the doc but not well enough emphasized, I'll fix that.

Indeed you can create a nested structure in your schema like that:

```ts
const schema = createSchema<target, source>({
  foo: {
    id: 'id'
  }
})
```
<img width="501" alt="Screen Shot 2019-11-08 at 4 38 29 PM" src="https://user-images.githubusercontent.com/4748419/68512493-92146d80-0246-11ea-8bdb-3a44961ffe37.png">

Please see a live example here: https://repl.it/@yrnd1/LostSpecializedFactorial

For your second question, providing the target being constructed was mostly a feature request for people who wanted to access it during the execution for some use cases. Here is the feature request https://github.com/nobrainr/morphism/pull/19 and here is an example of how it's used https://github.com/nobrainr/morphism/pull/19/files#diff-63ad4a525b2a60745244ae68c03f4b30R451
About the `source`, you can also use morphism on an object and also an array like `morphism(schema,[...items])`, so the idea is to provide the source in case where your action function is externalized and is not located close to the source so that you can access it, does it make sense ? :)

**Comment by C-Higgins** [comment]
Yep that all makes sense, thanks a lot.
