### ISSUE TITLE
Difference between an object with type and using createSchema

### ISSUE THREAD

**Issue by iangregsondev** [nobrainr/morphism#152]
Hi,

I have noticed there is 2 ways of creating a strictSchema, I was wondering what the difference is ?

```
export const groupPackageSchema = createSchema<GraphQL.GroupPackage, Responses.IGroupRoot>({
  groups: iteratee => morphism(groupSchema, iteratee._embedded.groups),
  pageInfo: morphism(pageInfoSchema)
})

export const groupPackageSchema: StrictSchema<GraphQL.GroupPackage, Responses.IGroupRoot> = {
  groups: iteratee => morphism(groupSchema, iteratee._embedded.groups),
  pageInfo: morphism(pageInfoSchema)
}
```

I didn't see anything specific in the docs with regards to why we should use createSchema ?

Thanks in advance

**Comment by emyann** [comment]
@iangregsondev Sorry for the delayed response, busy week. I'll definitely document this in the Readme.
But there is no fundamental differences between the 2 writings, `createSchema` is here to help with the typings first, so that if you don't specify any types, `morphism` will try to infer what is possible. And it provides you a way to specify a couple of options to `morphism` https://morphism.now.sh/modules/_morphismtree_#createschema, https://morphism.now.sh/interfaces/_morphismtree_.schemaoptions like how to handle `undefinedValues` 

<img width="841" alt="Screen Shot 2019-11-15 at 4 14 54 PM" src="https://user-images.githubusercontent.com/4748419/68976131-16c13780-07c3-11ea-953f-7ad664f3f9de.png">

Over the time, `createSchema` becomes to be the recommended approach to create a schema since it'll be possible to add more options to the processing steps. For example, like when the `Validation` feature gonna land in `v2` https://repl.it/@yrnd1/Morphism-Validation-Custom-Reporter-And-Formatter

Does it make sense ? :)

**Comment by iangregsondev** [comment]
great! yep makes total sense. Thanks.
