### ISSUE TITLE
[Question] Is there an easy way to apply the identity morphism?

### ISSUE THREAD

**Issue by mglezsosa** [nobrainr/morphism#185]
I was trying to figure out if there is a way to get an equal object except for, let's say, only one property that I want to map, without having to explicitly write every property.

Thanks!

**Comment by emyann** [comment]
Hello @mglezsosa,

To make sure I understand your request, is the use case you're looking for the following ?

```ts
const source = {
  a: 'something',
  b: 'something else'
}

const schema = {
   b: () => 'something different than source.b'
}

const result = morphism(schema, source)
// ==> 
// { a: 'something', b: 'something different than source.b' }
```

**Comment by mglezsosa** [comment]
Yep!

**Comment by emyann** [comment]
@mglezsosa Perfect! Yes it's possible if your `target` is an ES6 Class object:

You can see it working in this repl: https://repl.it/@yrnd1/UnequaledRotatingTraining, all you have to do is to run it to see the result.

```ts
import { morphism, createSchema } from 'morphism'

class Target {
  firstname: string = ''
  lastname: string = ''
}


const source = {
  firstname: 'firstname',
  lastname: 'lastname'
}

const schema = createSchema({
  lastname: () => 'custom lastname'
})

const result = morphism(schema, source, Target)

// ==>
// Target { firstname: 'firstname', lastname: 'custom lastname' }
```

One important note with this and could be error prone, in my opinion, is that all the properties should be initialized (at least with `undefined` values)  or definitely assigned in the constructor, otherwise it's not possible to know all the keys of the target.
Here's a more detailed explanation https://github.com/nobrainr/morphism/issues/74#issuecomment-493117755

At this time, If the `target` is not an ES6 Class object, `morphism` will only rely on the properties defined in the schema to build the target object. I could maybe add an option like `eager` to the `createSchema` to copy all the properties from the source to the target while taking the schema in account but I have the feeling it could be achieved with object merging in ES6 like:

```ts
const source = {
  firstname: 'firstname',
  lastname: 'lastname'
}

const schema = createSchema({
  lastname: () => 'custom lastname'
})

 const partial = morphism(schema, source)
// ==>
//  { lastname: 'custom lastname' }

const final = { ...source, ...partial }
// ==>
//  { firstname: 'firstname', lastname: 'custom lastname' }
```

Hope it helps!

**Comment by mglezsosa** [comment]
Awesome @emyann, thanks!
