### ISSUE TITLE
Map array to class objects array creates array with duplicate class objects

### ISSUE THREAD

**Issue by GuntherDebrauwer** [nobrainr/morphism#24]
I want to morph all items of an array to class objects using this package. The problem is that all generated class objects are the same: they all use the values of the last array item. I tried a couple of ways, but none seem to work. The only option that seems to work is resetting the mapper each time an item will be morphed.

Does anyone know what causes this issue or how it can be fixed?

```Javascript
class User {
  constructor(firstName, lastName, phoneNumber) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.phoneNumber = phoneNumber;
    this.city = null;
  }
}

// Data source you want to map
const data = [{
  firstName: 'John',
  lastName: 'Smith',
  address:
  {
    city: 'New York',
    country: 'USA'
  },
  phoneNumber:
  [
    {
      type: 'home',
      number: '212 555-1234',
    },
    {
      type: 'fax',
      number: '646 555-4567',
    },
  ],
},
{
  firstName: 'James',
  lastName: 'Bond',
  address:
  {
    city: 'New York',
    country: 'USA'
  },
  phoneNumber:
  [
    {
      type: 'home',
      number: '212 555-1234',
    },
    {
      type: 'fax',
      number: '646 555-4567',
    },
  ],
}];

import Morphism from 'morphism';

const schema = {
  city: 'adress.city',
  phoneNumber: object => object.phoneNumber.filter(c => c.type === 'home')[0].number,
};

const mapUser = Morphism.register(User, schema);

console.log(Morphism.map(User, data));
// both objects have the values from last data object --> not correct!

console.log(mapUser(data));
// same problem

console.log(data.map(item => Morphism.map(User, item)));
// same problem

console.log(data.map((item) => { Morphism.setMapper(User, schema); return Morphism.map(User, item); }));
// this works correctly
```

**Comment by emyann** [comment]
Thank you @GuntherDebrauwer for reporting this issue! 👍🏽

Indeed it's a regression brought by this feature https://github.com/nobrainr/morphism/pull/20/commits/c678a7d9385d22e7ee5b06d1e4a3507c8abb6372#diff-1426700f0fe9c2e114ef849801031386R131  where a mutation appeared on the created class object aimed to be processed.

This has been fixed here https://github.com/nobrainr/morphism/commit/6e64d05 in the release `0.9.1` https://github.com/nobrainr/morphism/releases

Here's a playground of your issue fixed by the latest version https://repl.it/@yrnd1/Morphism-GuntherDebrauwer

Thanks ⚡️
