### ISSUE TITLE
Stronger type for Schema

### ISSUE THREAD

**Issue by bossqone** [nobrainr/morphism#33]
Hello,
right now `Schema` type is defined as:
```ts
export interface Schema {
  /** `destinationProperty` is the name of the property of the target object you want to produce */
  [destinationProperty: string]: ActionString | ActionFunction | ActionAggregator | ActionSelector;
}
```
What do you think about changing it to:
```ts
export interface Schema<Target> {
  /** `destinationProperty` is the name of the property of the target object you want to produce */
  [destinationProperty in keyof Target]: ActionString | ActionFunction | ActionAggregator | ActionSelector;
}
```
It will enforce you to map all fields in the target type, so you won't miss any of them by mistake.

**Comment by emyann** [comment]
Hello @bossqone,

Thank you for this suggestion! In fact I was thinking about strengthening the link between the Schema and the Target type. Typescript interface does not accepts lookup in keys for index signature it will probably be
```ts
export type Schema<Target> = {
  /** `destinationProperty` is the name of the property of the target object you want to produce */
  [destinationProperty in keyof Target]?: ActionString | ActionFunction | ActionAggregator | ActionSelector
};
```
It will be like
<img width="673" alt="screen shot 2018-09-24 at 3 16 26 pm" src="https://user-images.githubusercontent.com/4748419/45974331-083c1d80-c00f-11e8-8978-bbfc1ed41e8a.png">

I don't want to enforce the consumer to specify each property since `Morphism` will automatically map properties when a Class Type is provided.

```ts
class Foo {
  foo: string;
  bar: string;
}
const schema = { foo: 'qux' };
const source = { qux: 'foo', bar: 'bar' };
const fooInstance = morphism(schema, source, Foo);
// bar will be mapped from source even if it's not in the schema
// => { foo: 'foo', bar: 'bar' }
```

I just opened a PR here https://github.com/nobrainr/morphism/pull/34, what do you think about ?

**Comment by bossqone** [comment]
I agree, that sounds reasonable.

**Comment by emyann** [comment]
<img width="802" alt="screen shot 2018-09-25 at 4 28 07 pm" src="https://user-images.githubusercontent.com/4748419/46043590-730c5800-c0e6-11e8-87de-512cafda829f.png">
