### ISSUE TITLE
Morphism.register and Morphism.Map map ALL properties

### ISSUE THREAD

**Issue by m4ss1m0g** [nobrainr/morphism#74]
# Step to reproduce
> morphism ^1.10.1

``` typescript
import Morphism, { morphism, StrictSchema } from "morphism";

// What we have
class Source {
    public id!: number;
    public ugly_field!: string;
}

// What we want
class Destination {
    public id?: number;
    public field!: string;
}

const source: Source = {
    id: 1,
    ugly_field: "field value"
};

const schema = { field: "ugly_field" };

const s: StrictSchema<Destination, Source> = schema;
Morphism.register(Destination, s);
const result = Morphism.map(Destination, source);
```
## Expected result 
``` typescript
expect(result.id).toBeUndefined();
``` 
## Actual result
``` typescript
result.id === 1
```

**Comment by emyann** [comment]
@m4ss1m0g Thank you for using Morphism and for this detailed report! 

I tried to reproduce this issue but was not able to have the `id` field mapped. The result I have is

```
Destination { field: 'field value' }
```

Please find the code you shared here tested with `morphism@1.10.1`: https://stackblitz.com/edit/typescript-xcm1dy?file=index.ts

Can you confirm this is something you noted with `^1.10.1` ? 

Thanks

**Comment by m4ss1m0g** [comment]
If I use **tsc** directly there are no errors; however with **webpack** there are the issue
I attach a simple project for repro
[morphTest.zip](https://github.com/nobrainr/morphism/files/3186121/morphTest.zip)

**Comment by emyann** [comment]
Ohhh Ok I think I got it! Thanks you for the hint! Here is a reproducible repl https://repl.it/@yrnd1/ContentImperturbableAlgorithm

You can run the code and open the console tab in the right window to see the output. 

To explain it: By design when you map towards an ES6 Class, Morphism finds the matching properties from the source in the Class (in this case `id`) and map the value like [Automapper](https://automapper.org/) would do for instance. The initial idea was to make transformations easier when the source properties and the ES6 Class target have matching properties.

To make this possible, we need to instantiate the class and grab the properties from the instance. This is what causing a different behaviour between `tsc` and `webpack`. With class properties initializer feature, the properties are initialized, and during the mapping Morphism find the corresponding properties in the ES6 Class and try to map the source values to them.

I concede this is misleading and I don't really like this initial choice 😕This is why the `Registry API` is planned to be removed in the [`v2`](https://github.com/nobrainr/morphism/issues/47). I could fix it to make it behave like the `morphism` function when used with interfaces only, but this could break some apps using this feature.

So my plan is to first introduce an option in [`createSchema`](https://morphism.now.sh/modules/_morphismtree_#createschema) helper allowing to skip this default mapping on ES6 Classes, and later introduce a breaking change by creating a `v2` then make the registry API obsolete.

While I am working to add this option and prepare the v2, what I could suggest you, if you don't absolutely need to create ES6 Objects is to use TypeScript interfaces instead:

``` 
import Morphism, { morphism, StrictSchema } from "morphism";

// What we have
class Source {
    public id!: number;
    public ugly_field!: string;
}

// What we want
interface Destination {
    id?: number;
    field: string;
}

const source: Source = {
    id: 1,
    ugly_field: "field value"
};

const schema: StrictSchema<Destination, Source> = { field: "ugly_field" };
const result = morphism(schema, source);
==>
// { field: 'field value' }
```
➡️https://repl.it/@yrnd1/SmoothSubstantialCalculator

If you absolutely need to have ES6 Objects, this is a bit ugly but you could specify each transformations in your schema to override this behaviour
```
const schema = { id: () => undefined, field: 'ugly_field' }
```

Hope this helps! Please let me know what you would choose as the best workaround for the moment.

Thanks again!

**Comment by m4ss1m0g** [comment]
Many thanks @emyann !!
I use Registry API because it is very similar to Automapper, what do you cold suggest to imitate a central repository like automapper without Registry API ?

**Comment by emyann** [comment]
@m4ss1m0g I added a new option to the schema in order to turn off the auto-mapping when you map towards Class objects. Here's the PR https://github.com/nobrainr/morphism/pull/81. Please take the time to look at the description in the Pull Request and let me know if this is ok for you.
You can use it with the `Registry API` or with the `morphism function` straight away.
